language: ruby
rvm:
- 2.3.1
sudo: false
before_script:
  - pip install --user yamllint
  - pip install --user yamale
  - pip install --user git+https://github.com/PandelisZ/pyyaml.git@allow-emojis
script:
  - yamllint _guestbook/*
  - ruby -Itest tests/tests.rb
  - bundle exec jekyll build
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
